# Generated by Django 2.2.2 on 2019-06-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descriptions', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
